<!DOCTYPE html>
<html>
<head>
  <title>Intro to R Workshop</title>
  <meta charset="utf-8">
  <meta name="description" content="Intro to R Workshop">
  <meta name="author" content="Sepehr Akhavan, Homer Strong, Zhe Yu">
  <meta name="generator" content="slidify" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/default.css" media="all" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/phone.css" 
    media="only screen and (max-device-width: 480px)" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/slidify.css" >
  <link rel="stylesheet" href="libraries/highlighters/highlight.js/css/tomorrow.css" />
  <base target="_blank"> <!-- This amazingness opens all links in a new tab. -->  <link rel=stylesheet href="./assets/css/logo.css"></link>
<link rel=stylesheet href="./assets/css/ribbons.css"></link>

  
  <!-- Grab CDN jQuery, fall back to local if offline -->
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
  <script>window.jQuery || document.write('<script src="libraries/widgets/quiz/js/jquery.js"><\/script>')</script> 
  <script data-main="libraries/frameworks/io2012/js/slides" 
    src="libraries/frameworks/io2012/js/require-1.0.8.min.js">
  </script>
  
  

</head>
<body style="opacity: 0">
  <slides class="layout-widescreen">
    
    <!-- LOGO SLIDE -->
        <slide class="title-slide segue nobackground">
  <aside class="gdbar">
    <img src="assets/img/logo.png">
  </aside>
  <hgroup class="auto-fadein">
    <h1>Intro to R Workshop</h1>
    <h2>UCI Data Science Initiative</h2>
    <p>Sepehr Akhavan, Homer Strong, Zhe Yu<br/>Dept. of Statistics</p>
  </hgroup>
    <a href="https://github.com/UCIDataScienceInitiative/IntroR_Workshop/zipball/gh-pages" class="example">
     Download
    </a>
  <article></article>  
</slide>
    

    <!-- SLIDES -->
    <slide class="" id="slide-1" style="background:;">
  <hgroup>
    <h2>Introduction</h2>
  </hgroup>
  <article data-timings="">
    <p>1) The class will include 5 sessions: </p>

<ul>
<li>Session 1 (9-10:20): Data Types in R </li>
<li>Session 2 (10:30-12): Control Structures and Functions</li>
<li>Session 3 (12:30-1:50): Statistical Distributions in R</li>
<li>Session 4 (2-3:20): Plotting and Data Visualization in R </li>
<li>Session 5 (3:30-5): Statistical Analysis in R</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-2" style="background:;">
  <hgroup>
    <h2>Introduction</h2>
  </hgroup>
  <article data-timings="">
    <p>2) We are going to work in pairs. Please find a partner. </p>

<p>3) Feel free to ask questions anytime during lectures.</p>

<p>5) To access this presentation and the codes used during the workshop please visit:</p>

<ul>
<li><a href="http://ucidatascienceinitiative.github.io/IntroR_Workshop/#1">http://ucidatascienceinitiative.github.io/IntroR_Workshop/#1</a></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-3" style="background:;">
  <hgroup>
    <h2>Session 1 - Agenda</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>RStudio</li>
<li>Data Types in R</li>
<li>Subsetting in R</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-4" style="background:;">
  <hgroup>
    <h2>What is R?</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>R is a free software environment for statistical computing and graphics</p>

<ul>
<li>See <a href="http://www.r-project.org/">http://www.r-project.org/</a> for more info</li>
</ul></li>
<li><p>R compiles and runs on a wide variety of UNIX platforms, Windows and Mac OS</p></li>
<li><p>R is Open-Source and free</p></li>
<li><p>R is fundamentally a command-driven system</p></li>
<li><p>R is an object-oriented programming language </p>

<ul>
<li>everything in R is considered as an object!</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-5" style="background:;">
  <hgroup>
    <h2>R Studio:</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li><p>RStudio is a free and open source integrated development environment (IDE) for R.</p></li>
<li><p>To download RStudio please visit: <a href="http://rstudio.org/">http://rstudio.org/</a></p></li>
<li><p>Please note that you must have R already installed before installing R Studio.</p></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-6" style="background:;">
  <hgroup>
    <h2>Data Types in R:</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li><p>R has 5 main atomic data types:</p>

<ul>
<li>Numeric</li>
<li>Integer</li>
<li>Complex</li>
<li>Logical</li>
<li>Character</li>
</ul></li>
<li><p>Everything in R is object. Objects can have some attributes.</p>

<ul>
<li>names, dimension, length are some possible attributes</li>
</ul></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-7" style="background:;">
  <hgroup>
    <h2>Vectors in R:</h2>
  </hgroup>
  <article data-timings="">
    <p>Vector is the most basic object in R</p>

<pre><code class="r">numVec &lt;- 1:10 # &lt;- : is assigning operator
numVec
</code></pre>

<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10
</code></pre>

<pre><code class="r">charVec &lt;- c(&quot;a&quot;, &quot;b&quot;, &quot;c&quot;) # c: to combine elements
charVec
</code></pre>

<pre><code>## [1] &quot;a&quot; &quot;b&quot; &quot;c&quot;
</code></pre>

<pre><code class="r">logVec &lt;- vector(mode = &quot;logical&quot;, length = 10)
logVec
</code></pre>

<pre><code>##  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-8" style="background:;">
  <hgroup>
    <h3>Special Values:</h3>
  </hgroup>
  <article data-timings="">
    <p>There are some special values in R:</p>

<ul>
<li>use L to refer to an integer value: 1L</li>
<li>R knows infinity: Inf, -Inf</li>
<li>NaN: refers to &quot;Not a number&quot;</li>
</ul>

<pre><code class="r">intVec &lt;- c(1L, 2L, 3L, 4L) 
intVec
</code></pre>

<pre><code>## [1] 1 2 3 4
</code></pre>

<pre><code class="r">a &lt;- Inf; b &lt;- 0
rslt &lt;- c(b/a, a/a)
rslt
</code></pre>

<pre><code>## [1]   0 NaN
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-9" style="background:;">
  <hgroup>
    <h3>Logical, Complex, &amp; Character Vectors:</h3>
  </hgroup>
  <article data-timings="">
    <p>Let&#39;s see some examples of logical, complex, and character vectors:</p>

<pre><code class="r">logVec &lt;- c(TRUE, FALSE, FALSE, T, F)
logVec
</code></pre>

<pre><code>## [1]  TRUE FALSE FALSE  TRUE FALSE
</code></pre>

<pre><code class="r">compVec &lt;- c(1 + 0i, 3 + 1i)
compVec
</code></pre>

<pre><code>## [1] 1+0i 3+1i
</code></pre>

<pre><code class="r">charVec &lt;- c(&quot;red&quot;, &quot;green&quot;, &quot;blue&quot;)
charVec
</code></pre>

<pre><code>## [1] &quot;red&quot;   &quot;green&quot; &quot;blue&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-10" style="background:;">
  <hgroup>
    <h3>Data Type Coercion:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>In general, vectors CAN NOT have mixed types of objects</li>
<li>exception: lists in R </li>
</ul>

<pre><code class="r">numCharVec &lt;- c(3.14, &quot;a&quot;)
numCharVec # ? what would you expect to be printed?

numLogVec &lt;- c(pi, T)
numLogVec # any guess?

charLogVec &lt;- c(&quot;a&quot;, TRUE)
charLogVec # ?
</code></pre>

<ul>
<li>In examples above, we saw implicit coercion </li>
<li>Explicit coercion is also possible!</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-11" style="background:;">
  <hgroup>
    <h3>Data Type Coercion:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>as(): To explicitly coerce objects from one type to another</li>
</ul>

<pre><code class="r">numVec &lt;- seq(from = 1200, to = 1300, by = 15)
numVec
</code></pre>

<pre><code>## [1] 1200 1215 1230 1245 1260 1275 1290
</code></pre>

<pre><code class="r">numToChar &lt;- as(numVec, &quot;character&quot;)
numToChar
</code></pre>

<pre><code>## [1] &quot;1200&quot; &quot;1215&quot; &quot;1230&quot; &quot;1245&quot; &quot;1260&quot; &quot;1275&quot; &quot;1290&quot;
</code></pre>

<pre><code class="r">logVec &lt;- c(F, T, F, T, T)
as(logVec, &quot;numeric&quot;)
</code></pre>

<pre><code>## [1] 0 1 0 1 1
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-12" style="background:;">
  <hgroup>
    <h3>Data Type Coercion:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Coercion does not always work! Be careful about warnings:</li>
</ul>

<pre><code class="r">compVec &lt;- c(12+10i, 1+6i, -3-2i)
as(compVec, &quot;numeric&quot;)
</code></pre>

<pre><code>## Warning: imaginary parts discarded in coercion
</code></pre>

<pre><code>## [1] 12  1 -3
</code></pre>

<pre><code class="r">charVec &lt;- c(&quot;2.5&quot;, &quot;3&quot;, &quot;2.8&quot;, &quot;1.5&quot;, &quot;zero&quot;)
as(charVec, &quot;numeric&quot;)
</code></pre>

<pre><code>## Warning: NAs introduced by coercion
</code></pre>

<pre><code>## [1] 2.5 3.0 2.8 1.5  NA
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-13" style="background:;">
  <hgroup>
    <h3>Factors:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Factor is a vector object used to specify a discrete classification (categorical values).</li>
<li>Factors can be: 1) ordered, 2) un-ordered</li>
<li>Levels of a Factor are better to be labeled (self-descriptive)

<ul>
<li>Consider gender as (0, 1) as opposed to labeled (&quot;F&quot;, &quot;M&quot;)</li>
</ul></li>
</ul>

<pre><code class="r">Gender &lt;- rep(c(&quot;Female&quot;, &quot;Male&quot;), times = 3)
Gender
</code></pre>

<pre><code>## [1] &quot;Female&quot; &quot;Male&quot;   &quot;Female&quot; &quot;Male&quot;   &quot;Female&quot; &quot;Male&quot;
</code></pre>

<pre><code class="r">GenderFac1 &lt;- factor(Gender)
GenderFac1
</code></pre>

<pre><code>## [1] Female Male   Female Male   Female Male  
## Levels: Female Male
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-14" style="background:;">
  <hgroup>
    <h3>Factors:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">levels(GenderFac1)
</code></pre>

<pre><code>## [1] &quot;Female&quot; &quot;Male&quot;
</code></pre>

<pre><code class="r">table(GenderFac1)
</code></pre>

<pre><code>## GenderFac1
## Female   Male 
##      3      3
</code></pre>

<pre><code class="r">unclass(GenderFac1) # bring the factor down to integer values
</code></pre>

<pre><code>## [1] 1 2 1 2 1 2
## attr(,&quot;levels&quot;)
## [1] &quot;Female&quot; &quot;Male&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-15" style="background:;">
  <hgroup>
    <h3>Factors:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">GenderFac1 # levels are ordered alphabetically - 1st level = BaseLevel
</code></pre>

<pre><code>## [1] Female Male   Female Male   Female Male  
## Levels: Female Male
</code></pre>

<pre><code class="r">GenderFac2 &lt;- factor(Gender, levels = c(&quot;Male&quot;, &quot;Female&quot;))
GenderFac1
</code></pre>

<pre><code>## [1] Female Male   Female Male   Female Male  
## Levels: Female Male
</code></pre>

<pre><code class="r">GenderFac2
</code></pre>

<pre><code>## [1] Female Male   Female Male   Female Male  
## Levels: Male Female
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-16" style="background:;">
  <hgroup>
    <h3>Missing Values:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>There are two kinds of missing values in R:</p>

<ul>
<li>NaN: refers to &quot;Not a Number&quot; and is a a missing value produced by numerical computation.</li>
<li>NA: When a value is &quot;Not Available&quot; or is &quot;Missing&quot;, NA is assigned as its value.</li>
</ul></li>
<li><p>NaN is also considered as NA (the reverse is NOT true). </p></li>
</ul>

<pre><code class="r">testScore &lt;- NA
is.na(testScore)
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<pre><code class="r">is.nan(testScore)
</code></pre>

<pre><code>## [1] FALSE
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-17" style="background:;">
  <hgroup>
    <h3>Matrices:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Matrix is a special case of vector:

<ul>
<li>Matrix has dimension attribute</li>
</ul></li>
</ul>

<pre><code class="r">myMat &lt;- matrix(nrow = 2, ncol = 4)
myMat
</code></pre>

<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   NA   NA   NA   NA
## [2,]   NA   NA   NA   NA
</code></pre>

<pre><code class="r">attributes(myMat)
</code></pre>

<pre><code>## $dim
## [1] 2 4
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-18" style="background:;">
  <hgroup>
    <h3>Matrices:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myMat &lt;- matrix(1:8, nrow = 2, ncol = 4)
myMat # matrices are filled in column-wise
</code></pre>

<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    7
## [2,]    2    4    6    8
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-19" style="background:;">
  <hgroup>
    <h3>Matrix is a special vector:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myVec &lt;- 1:8
myVec
</code></pre>

<pre><code>## [1] 1 2 3 4 5 6 7 8
</code></pre>

<pre><code class="r">dim(myVec) &lt;- c(2,4)
myVec
</code></pre>

<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    7
## [2,]    2    4    6    8
</code></pre>

<ul>
<li>Similar to vectors, all elements of a matrix should have the same type.

<ul>
<li>if not, R does an automatic coercion.</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-20" style="background:;">
  <hgroup>
    <h3>Other Ways to Create Matrix:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>As it&#39;s intuitive, matrices seem to be a combination of vectors that are put next to each other (either column wise or row wise).</p></li>
<li><p>rbind() (row bind) and cbind (column bind) do a similar job:</p></li>
</ul>

<pre><code class="r">vec1 &lt;- 1:4
vec2 &lt;- sample(1:100, 4, replace = FALSE)
vec3 &lt;- rnorm(4, mean = 0, sd = 1)
colMat &lt;- cbind(vec1, vec2, vec3)
colMat
</code></pre>

<pre><code>##      vec1 vec2     vec3
## [1,]    1   88 -0.60388
## [2,]    2   64 -0.07985
## [3,]    3   74  0.89368
## [4,]    4   55  1.85324
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-21" style="background:;">
  <hgroup>
    <h3>Other Ways to Create Matrix:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">vec1 &lt;- 1:4
vec2 &lt;- sample(1:100, 4, replace = FALSE)
vec3 &lt;- rnorm(4, mean = 0, sd = 1)
rowMat &lt;- rbind(vec1, vec2, vec3)
rowMat
</code></pre>

<pre><code>##         [,1]    [,2]   [,3] [,4]
## vec1  1.0000  2.0000  3.000 4.00
## vec2 21.0000 62.0000 74.000 9.00
## vec3  0.6717  0.1932 -2.489 1.09
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-22" style="background:;">
  <hgroup>
    <h2>Lists:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Consider list as a vector but with two main differences:

<ul>
<li>each element of a list can have its own class regardless of other elements</li>
<li>This means, each element can be of a different data type and a different length</li>
</ul></li>
</ul>

<pre><code class="r">myVec &lt;- c(10, &quot;R&quot;, 10-5i, T)
myList &lt;- list(10, &quot;R&quot;, 10-5i, T)
myVec
</code></pre>

<pre><code>## [1] &quot;10&quot;    &quot;R&quot;     &quot;10-5i&quot; &quot;TRUE&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-23" style="background:;">
  <hgroup>
    <h2>Lists:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myList &lt;- list(10, &quot;R&quot;, 10-5i, T)
myList
</code></pre>

<pre><code>## [[1]]
## [1] 10
## 
## [[2]]
## [1] &quot;R&quot;
## 
## [[3]]
## [1] 10-5i
## 
## [[4]]
## [1] TRUE
</code></pre>

<ul>
<li>Elements of list are shown with [[]]</li>
<li>Elements of vector are shown with []</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-24" style="background:;">
  <hgroup>
    <h2>Data Frames:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>We use data frames to store tabular data</li>
<li>Data frame is a special list where all objects have equal length</li>
<li>The main difference between data.frame and Matrix?</li>
</ul>

<pre><code class="r">studentID &lt;- paste(&quot;S#&quot;, sample(c(6473:7392), 10), sep = &quot;&quot;)
score &lt;- sample(c(0:100), 10)
gender &lt;- sample(c(&quot;female&quot;, &quot;male&quot;), 10, replace = TRUE)
data &lt;- data.frame(studentID = studentID, score = score, gender = gender)
head(data)
</code></pre>

<pre><code>##   studentID score gender
## 1    S#7075    74 female
## 2    S#6834    68 female
## 3    S#7282    10   male
## 4    S#6903    18 female
## 5    S#7067    98   male
## 6    S#7026     7   male
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-25" style="background:;">
  <hgroup>
    <h2>Subsetting:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Often times we need to take a subset of a vector, a matrix, a list, or a dataframe.</li>
<li><p>We consider three main operators to take a subset of an object:</p>

<ul>
<li>[ ]: single brackets return an object of the same class of the original object. By using [], we can also choose more than one element.</li>
<li>[[ ]]: double brackets are used primarily for lists and dataframes. </li>
<li>&quot;$&quot;: is used primarily for lists and dataframes (similar to double brackets). </li>
</ul></li>
<li><p>With [[ ]] and $, we can only choose one object!</p></li>
<li><p>[[ ]] and $ can return an object with a different class than the original objects we are subsetting from.</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-26" style="background:;">
  <hgroup>
    <h3>Subsetting examples:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myVec &lt;- 10:20
myVec[3]
</code></pre>

<pre><code>## [1] 12
</code></pre>

<pre><code class="r">myList &lt;- list(obj1 = &quot;a&quot;, obj2 = 10, obj3 = T, obj4 = 10-5i)
myList[[3]]
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<pre><code class="r">myList$obj3
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-27" style="background:;">
  <hgroup>
    <h2>Subsetting with [ ]:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>By using single bracket, we can choose more than one element of an object.</li>
<li>In this case, index vectors can be very useful:

<ul>
<li>Index vector is a vector of indices of another vector that is used to select a subset of another vector (or Matrix)</li>
</ul></li>
</ul>

<pre><code class="r">x &lt;- seq(from=0, to=100,by=10) # length(x) is ??
IndVec &lt;- c(1, 2, 3, 4, 5) # the first 5 elements 
x[IndVec]
</code></pre>

<pre><code>## [1]  0 10 20 30 40
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-28" style="background:;">
  <hgroup>
    <h2>Index Vectors:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>There are four types of Index vectors:

<ol>
<li>Logical Index Vector: The logical index vector should be of the same length of the vector from which we are selecting a subset. Values corresponding to TRUE in the index vector are selected.</li>
<li>Vector of Positive integers: All the values in this type of index vector must lie in 1:(length(x)).</li>
<li>Vector of Negative integers: This type of index vector indicates the values to be excluded from the
vector.</li>
<li>A Vector of Character Strings: if a vector has a name attribute, we can simply take a subset of the vector by calling the names of the elements.</li>
</ol></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-29" style="background:;">
  <hgroup>
    <h2>Index Vectors:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myVec &lt;- letters[1:10]
names(myVec) &lt;- paste(&quot;e&quot;, 1:10, sep = &quot;&quot;)
myVec
</code></pre>

<pre><code>##  e1  e2  e3  e4  e5  e6  e7  e8  e9 e10 
## &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot; &quot;f&quot; &quot;g&quot; &quot;h&quot; &quot;i&quot; &quot;j&quot;
</code></pre>

<pre><code class="r">logIndVec &lt;- rep(c(T, F), each = 5)
logIndVec
</code></pre>

<pre><code>##  [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE
</code></pre>

<pre><code class="r">posIndVec &lt;- 1:5
negIndVec &lt;- -6:-10
chIndVec &lt;- c(&quot;e1&quot;, &quot;e2&quot;, &quot;e3&quot;, &quot;e4&quot;, &quot;e5&quot;)
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-30" style="background:;">
  <hgroup>
    <h2>Index Vectors:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myVec[logIndVec]
</code></pre>

<pre><code>##  e1  e2  e3  e4  e5 
## &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot;
</code></pre>

<pre><code class="r">myVec[negIndVec]
</code></pre>

<pre><code>##  e1  e2  e3  e4  e5 
## &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot;
</code></pre>

<pre><code class="r">myVec[chIndVec]
</code></pre>

<pre><code>##  e1  e2  e3  e4  e5 
## &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-31" style="background:;">
  <hgroup>
    <h2>Logical Index Vectors:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>logical index vectors can be generated by using conditional statements:

<ul>
<li>Using ==, !=, &lt;, &gt;, ...</li>
</ul></li>
</ul>

<pre><code class="r">myVec &lt;- 1:10
logIndVec &lt;- (myVec &lt; 5)
logIndVec
</code></pre>

<pre><code>##  [1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
</code></pre>

<pre><code class="r">myVec[logIndVec]
</code></pre>

<pre><code>## [1] 1 2 3 4
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-32" style="background:;">
  <hgroup>
    <h2>Matrix Indexing:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Similar to vector indexing, we can refer to individual elements of a matrix.</li>
</ul>

<pre><code class="r">myMat &lt;- matrix(1:8, ncol = 4)
myMat
</code></pre>

<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    7
## [2,]    2    4    6    8
</code></pre>

<pre><code class="r">myMat[1,1] # refering to an element
</code></pre>

<pre><code>## [1] 1
</code></pre>

<pre><code class="r">myMat[2,] # refering to the second row
</code></pre>

<pre><code>## [1] 2 4 6 8
</code></pre>

<pre><code class="r">myMat[,3] # refering to the third column
</code></pre>

<pre><code>## [1] 5 6
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-33" style="background:;">
  <hgroup>
    <h2>Matrix Indexing:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>By default, when the retrieved elements of a matrix look like a vector, R drops their dimension attribute. We can turn this feature off by setting drop = FALSE</li>
</ul>

<pre><code class="r">myMat[1,1]
</code></pre>

<pre><code>## [1] 1
</code></pre>

<pre><code class="r">myMat[1,1, drop = FALSE]
</code></pre>

<pre><code>##      [,1]
## [1,]    1
</code></pre>

<pre><code class="r">myMat[2,, drop = FALSE]
</code></pre>

<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    2    4    6    8
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-34" style="background:;">
  <hgroup>
    <h2>Subsetting Lists:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myList &lt;- list(ch = letters[1:2], lg = F, nm = 1:3)
myList
</code></pre>

<pre><code>## $ch
## [1] &quot;a&quot; &quot;b&quot;
## 
## $lg
## [1] FALSE
## 
## $nm
## [1] 1 2 3
</code></pre>

<pre><code class="r">myList[1] # subset is still a list
</code></pre>

<pre><code>## $ch
## [1] &quot;a&quot; &quot;b&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-35" style="background:;">
  <hgroup>
    <h2>Subsetting Lists:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myList[1:2] # subset is still a list
</code></pre>

<pre><code>## $ch
## [1] &quot;a&quot; &quot;b&quot;
## 
## $lg
## [1] FALSE
</code></pre>

<pre><code class="r">myList[[1]] # returning the 1st obj with its own class
</code></pre>

<pre><code>## [1] &quot;a&quot; &quot;b&quot;
</code></pre>

<pre><code class="r">myList$ch # alternative to [[]]
</code></pre>

<pre><code>## [1] &quot;a&quot; &quot;b&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-36" style="background:;">
  <hgroup>
    <h2>Subsetting Lists:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myList[[1]][2] # returning the 2nd element of the 1st obj
</code></pre>

<pre><code>## [1] &quot;b&quot;
</code></pre>

<pre><code class="r">myList$ch[2]
</code></pre>

<pre><code>## [1] &quot;b&quot;
</code></pre>

<pre><code class="r">myList[[c(1,2)]]
</code></pre>

<pre><code>## [1] &quot;b&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-37" style="background:;">
  <hgroup>
    <h2>Subsetting Data Frames:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">library(datasets)
data(quakes) # ?quakes for more info
str(quakes)
</code></pre>

<pre><code>## &#39;data.frame&#39;:    1000 obs. of  5 variables:
##  $ lat     : num  -20.4 -20.6 -26 -18 -20.4 ...
##  $ long    : num  182 181 184 182 182 ...
##  $ depth   : int  562 650 42 626 649 195 82 194 211 622 ...
##  $ mag     : num  4.8 4.2 5.4 4.1 4 4 4.8 4.4 4.7 4.3 ...
##  $ stations: int  41 15 43 19 11 12 43 15 35 19 ...
</code></pre>

<pre><code class="r">head(quakes$long)
</code></pre>

<pre><code>## [1] 181.6 181.0 184.1 181.7 182.0 184.3
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-38" style="background:;">
  <hgroup>
    <h2>Subsetting Data Frames:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">quakes[1:10,]
</code></pre>

<pre><code>##       lat  long depth mag stations
## 1  -20.42 181.6   562 4.8       41
## 2  -20.62 181.0   650 4.2       15
## 3  -26.00 184.1    42 5.4       43
## 4  -17.97 181.7   626 4.1       19
## 5  -20.42 182.0   649 4.0       11
## 6  -19.68 184.3   195 4.0       12
## 7  -11.70 166.1    82 4.8       43
## 8  -28.11 181.9   194 4.4       15
## 9  -28.74 181.7   211 4.7       35
## 10 -17.47 179.6   622 4.3       19
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-39" style="background:;">
  <hgroup>
    <h2>Time to Break for 10 Minutes :)</h2>
  </hgroup>
  <article data-timings="">
    
  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-40" style="background:;">
  <hgroup>
    <h2>Session 2 - Agenda</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>Vectorized Operations in R</li>
<li>Reading and Writing in R</li>
<li>Control Structure</li>
<li>Functions &amp; Packages</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-41" style="background:;">
  <hgroup>
    <h2>Vectorized Operations</h2>
  </hgroup>
  <article data-timings="">
    <p>R is capable of vectorized operations without any need for running loops:</p>

<pre><code class="r">x &lt;- 1:5
y &lt;- c(1, 2, 6, 7, 10)
x + y # R does an element by element summation
</code></pre>

<pre><code>## [1]  2  4  9 11 15
</code></pre>

<pre><code class="r">x &lt; y
</code></pre>

<pre><code>## [1] FALSE FALSE  TRUE  TRUE  TRUE
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-42" style="background:;">
  <hgroup>
    <h2>Vectorized Operations</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Similar to vectors, vectorized operations can be performed for Matrices:</li>
</ul>

<pre><code class="r">x &lt;- matrix(1:9, ncol = 3)
y &lt;- matrix(rep(c(5,6,7), 3), ncol = 3)
x + y # R does an element by element summation
</code></pre>

<pre><code>##      [,1] [,2] [,3]
## [1,]    6    9   12
## [2,]    8   11   14
## [3,]   10   13   16
</code></pre>

<pre><code class="r">x &lt; y
</code></pre>

<pre><code>##      [,1] [,2]  [,3]
## [1,] TRUE TRUE FALSE
## [2,] TRUE TRUE FALSE
## [3,] TRUE TRUE FALSE
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-43" style="background:;">
  <hgroup>
    <h2>Reading and Writing Data</h2>
  </hgroup>
  <article data-timings="">
    <p><strong>The slides for &quot;Reading and Writing Data&quot; section were mainly from Dr. Roger D. Peng, Associate Professor at Johns Hopkins</strong></p>

<p>Main functions for reading data into R:</p>

<ol>
<li>read.table(), read.csv(): to read tabular data </li>
<li>readLines(): to read lines of a text file</li>
<li>source(), dget(): reading R codes</li>
<li>load(): to read saved workspaces</li>
</ol>

<ul>
<li>Only read.table() and read.csv() are covered in this lecture. </li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-44" style="background:;">
  <hgroup>
    <h2>Reading and Writing Data</h2>
  </hgroup>
  <article data-timings="">
    <p>Main functions for writing data from R:</p>

<ol>
<li>write.table(), write.csv(): to write tabular data to file</li>
<li>writeLines(): to write lines to a text file</li>
<li>dump, dput: to write R codes to a file</li>
<li>save: to save a workspace</li>
</ol>

<ul>
<li>Only write.table() is covered in this lecture. </li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-45" style="background:;">
  <hgroup>
    <h2>read.table():</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>read.table() is the most commonly used function to read data in R. Below are important arguments of this function:</p>

<ul>
<li>file: name or address to the file of interest</li>
<li>header: logical indicator on whether the file has header or not</li>
<li>sep: string on how columns of data are separated (in .csv, sep = &quot;,&quot;)</li>
<li>colClasses: is a character vector for class of each column</li>
<li>nrows: number of rows in the dataset</li>
<li>comment.char: a character that is used in the dataset for commenting</li>
<li>skip: number of lines to skip from the beginning of the file</li>
<li>stringAsFactors: logical indicator on whether characters should be converted to factors </li>
</ul></li>
<li><p>read.csv() is equivalent to read.table with sep = &quot;,&quot; and header = TRUE</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-46" style="background:;">
  <hgroup>
    <h2>read.table():</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">irisFile &lt;- read.table(file = &quot;/Users/sepehrakhavan/Documents/R_Workshop/iris.csv&quot;, header = TRUE)
</code></pre>

<pre><code>## Warning: cannot open file
## &#39;/Users/sepehrakhavan/Documents/R_Workshop/iris.csv&#39;: No such file or
## directory
</code></pre>

<pre><code>## Error: cannot open the connection
</code></pre>

<pre><code class="r">head(irisFile)
</code></pre>

<pre><code>## Error: object &#39;irisFile&#39; not found
</code></pre>

<ul>
<li>to make read.table() run faster:

<ul>
<li>set comment.char = &quot; &quot;</li>
<li>set colClasses upfront</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-47" style="background:;">
  <hgroup>
    <h2>Calculating Memory Requirements:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>Note that datasets will be read into RAM. So, you should have enough RAM in order to read a dataset. </p></li>
<li><p>Consider a data frame with 1.5 million rows and 120 columns. How much memory is required to read this dataset?</p></li>
</ul>

<p>1.5m * 120 * 8 bytes/numeric = 1.44 * \(10^9\) = 1.44 * \(10^9\)/ \(2^{20}\) MB = 1,373.29 MB = 1.34 GB</p>

<ul>
<li>So it&#39;s recommended to have a RAM of size 2 * 1.34GB to read that dataset.</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-48" style="background:;">
  <hgroup>
    <h2>write.table():</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">write.table(irisFile, file = &quot;path/to/the/file&quot;)
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-49" style="background:;">
  <hgroup>
    <h2>Loops:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>There are 3 ways in R to write loops:

<ul>
<li>for </li>
<li>repeat (skipped!)</li>
<li>while (skipped!)</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-50" style="background:;">
  <hgroup>
    <h3>for:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">for(i in 1:4){
  print(paste(&quot;cycle #&quot;, i, sep = &quot;&quot;))
  i &lt;- i + 1 
}
</code></pre>

<pre><code>## [1] &quot;cycle #1&quot;
## [1] &quot;cycle #2&quot;
## [1] &quot;cycle #3&quot;
## [1] &quot;cycle #4&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-51" style="background:;">
  <hgroup>
    <h2>if:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>if/else statements are used to write conditional statements</li>
</ul>

<pre><code class="r">x &lt;- 7
if (x &lt; 10){
  print(&quot;x is less than 10&quot;)
}else{
  print(&quot;x is greater than 10&quot;)
}
</code></pre>

<pre><code>## [1] &quot;x is less than 10&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-52" style="background:;">
  <hgroup>
    <h2>if:</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">age &lt;- sample(1:100, 10)
ageCat &lt;- rep(NA, length(age))
for (i in 1:(length(age))) {
    if (age[i] &lt;= 35){
       ageCat[i] &lt;- &quot;Young&quot;
      }else if (age[i] &lt;= 55){
        ageCat[i] &lt;- &quot;Middle-Aged&quot;
      }else{
         ageCat[i] &lt;- &quot;Old&quot;
      } 
}
age.df &lt;- data.frame(age = age, ageCat = ageCat)
age.df[1:3,]
</code></pre>

<pre><code>##   age      ageCat
## 1  51 Middle-Aged
## 2  30       Young
## 3  34       Young
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-53" style="background:;">
  <hgroup>
    <h2>Functions and Packages:</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>R language has many built-in functions</li>
<li>Each function has a name followed by ()</li>
<li>Arguments of a function should mention within parentheses</li>
<li>R packages are a comfortable way to maintain collections of R functions and data sets</li>
<li>Packages allow for easy, transparent and cross-platform extension of the R base system</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-54" style="background:;">
  <hgroup>
    <h2>Functions and Packages:</h2>
  </hgroup>
  <article data-timings="">
    <p>There are some terms which sometimes get confused and should be clarified:</p>

<ol>
<li>Package: An extension of the R base system with code, data and documentation in a standardized format</li>
<li>Library: A directory containing installed packages</li>
<li>Repository: A website providing packages for installation</li>
<li>Source: The original version of a package with human-readable text and code</li>
<li>Base packages: Part of the R source tree, maintained by R Core</li>
</ol>

<ul>
<li>for more info on how R packages are developed, please read: &quot;Creating R Packages: A Tutorial&quot; (Friedrich Leisch)

<ul>
<li><a href="http://cran.r-project.org/doc/contrib/Leisch-CreatingPackages.pdf">http://cran.r-project.org/doc/contrib/Leisch-CreatingPackages.pdf</a></li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-55" style="background:;">
  <hgroup>
    <h2>How to install a package in R:</h2>
  </hgroup>
  <article data-timings="">
    <p>There are three main ways to install a package in R:</p>

<ol>
<li><p>Installing from CRAN: install a package directly from the repository</p>

<ul>
<li>Using R studio: tools/install packages</li>
<li>From R console: install.packages()</li>
</ul></li>
<li><p>Installing from Source: In this method, you should first download the add-on R package and use the following unix command in the console to install the package:</p>

<ul>
<li>R CMD INSTALL packageName -l path/to/your/Rpackage/Directory</li>
</ul></li>
<li><p>Installing from a version control (Github): </p>

<ul>
<li>Check-out <a href="https://github.com/hadley/devtools">https://github.com/hadley/devtools</a></li>
</ul></li>
</ol>

<ul>
<li>Once you install a package, you need to load it into R using the function library()</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-56" style="background:;">
  <hgroup>
    <h2>Popular Packages in R:</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li><p>To visualize data:</p>

<ul>
<li>ggplot2: to create beautiful graphics</li>
<li>googleVis: to use Google Chart tools</li>
</ul></li>
<li><p>To report results:</p>

<ul>
<li>shiny: to create interactive web-based apps</li>
<li>knitr: to combine R codes and Latex/Markdown codes</li>
<li>slidify: to build HTML 5 slide shows</li>
</ul></li>
<li><p>To write high-performance R code:</p>

<ul>
<li>Rcpp: to write R functions that call C++ code</li>
<li>data.table: to organize datasets for fast operations</li>
<li>parallel: to use parallel processing in R</li>
</ul></li>
</ol>

<hr>

<h2>Calling a function in R</h2>

<pre><code class="r">str(sample)
</code></pre>

<pre><code>## function (x, size, replace = FALSE, prob = NULL)
</code></pre>

<ul>
<li>consider sample() in R. Simply run ?sample in R console to read the help on this function.</li>
<li><p>sample() gets four arguments: </p>

<ul>
<li>x: sample space in form of a vector</li>
<li>size: your desired sample size</li>
<li>replace: sampling with/without replacement</li>
<li>prob: a vector of probability weights</li>
</ul></li>
<li><p>some of the arguments have default values. What are those arguments?</p></li>
<li><p>How to use (or call) this function? </p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-57" style="background:;">
  <hgroup>
    <h2>Calling a function in R</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r"># Functions arguments can be matched: 1) by position or 2) by name
sampSpace &lt;- 1:6 # rolling a die
sample(sampSpace, 1) # arguments with default values can be omitted
</code></pre>

<pre><code>## [1] 4
</code></pre>

<pre><code class="r">sample(size = 1, x = sampSpace) # no need to remember the order 
</code></pre>

<pre><code>## [1] 1
</code></pre>

<pre><code class="r">sample(size = 1, sampSpace)
</code></pre>

<pre><code>## [1] 1
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-58" style="background:;">
  <hgroup>
    <h2>Writing your Own functions</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">yourFnName &lt;- function(&lt;your arguments&gt;){
  # body of your code

  # return the output of the function
}

# to use your function, you can simply call the function name as:
yourFnName(&lt;set values for the input arguments&gt;)
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-59" style="background:;">
  <hgroup>
    <h2>Writing your Own functions</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Let&#39;s write a function that gets three arguments: a, b, c</li>
<li>The function then returns min of these two numbers</li>
</ul>

<pre><code class="r">myMin &lt;- function(a, b, c){
  myMinVal &lt;- min(a, b, c)
  return(myMinVal)
}

myMin(10, 20, 30)
</code></pre>

<pre><code>## [1] 10
</code></pre>

<pre><code class="r">myMin(10, NA, 20) # ? how to fix this so it returns 10
</code></pre>

<pre><code>## [1] NA
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-60" style="background:;">
  <hgroup>
    <h2>Some notes on Functions</h2>
  </hgroup>
  <article data-timings="">
    <ol class = "build incremental">
<li><p>Variables defined within a function are locally defined (i.e. not defined outside of the function).</p></li>
<li><p>Functions in R are treated like any other first class objects. This means functions can be passed as arguments of other functions.</p></li>
<li><p>Arguments of functions are evaluated as they are needed (lazy evaluation). </p></li>
<li><p>&quot; ... &quot; can be an argument of a function and it refers to a situation where number of input arguments can be varied and is not fixed upfront. </p></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-61" style="background:;">
  <hgroup>
    <h2>Lazy Evaluation of Function Arguments</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myLazyFn1 &lt;- function(a, b){
  return(a)
}
myLazyFn1(10) # No error!
</code></pre>

<pre><code>## [1] 10
</code></pre>

<pre><code class="r">myLazyFn2 &lt;- function(a, b){
  print(a)
  print(b)
  return(1)
}
myLazyFn2(10) # No error!
</code></pre>

<pre><code>## [1] 10
</code></pre>

<pre><code>## Error: argument &quot;b&quot; is missing, with no default
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-62" style="background:;">
  <hgroup>
    <h2>Some useful functions:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Here we are going to talk about:

<ul>
<li>str(): a function to explain internal structure of a function</li>
<li>apply(): to apply a function to a matrix or dataframe</li>
<li>lapply(), sapply(), tapply(), mapply(): applying a function to a vector</li>
<li>split(): to split a dataset by levels of a factor</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-63" style="background:;">
  <hgroup>
    <h3>str():</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>str() is a compact way of understanding what an object is and what is in that object.</li>
</ul>

<pre><code class="r">str(str)
</code></pre>

<pre><code>## function (object, ...)
</code></pre>

<pre><code class="r">str(sample)
</code></pre>

<pre><code>## function (x, size, replace = FALSE, prob = NULL)
</code></pre>

<pre><code class="r">genderF &lt;- factor(sample(c(&quot;Male&quot;, &quot;Female&quot;), 20, replace = TRUE))
str(genderF)
</code></pre>

<pre><code>##  Factor w/ 2 levels &quot;Female&quot;,&quot;Male&quot;: 1 2 1 2 1 1 1 2 2 1 ...
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-64" style="background:;">
  <hgroup>
    <h3>str():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myMat &lt;- matrix(1:10, ncol = 5)
str(myMat)
</code></pre>

<pre><code>##  int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
</code></pre>

<pre><code class="r">myList &lt;- list(numVec = 1:3, logVec = F, charVec = LETTERS[1:4])
str(myList)
</code></pre>

<pre><code>## List of 3
##  $ numVec : int [1:3] 1 2 3
##  $ logVec : logi FALSE
##  $ charVec: chr [1:4] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-65" style="background:;">
  <hgroup>
    <h3>apply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(apply) # try ?apply for more info
</code></pre>

<pre><code>## function (X, MARGIN, FUN, ...)
</code></pre>

<ul>
<li><p>apply() is a useful function to apply a function (FUN) on a MARGIN of a matrix or dataframe (X)</p></li>
<li><p>MARGIN: a vector giving the subscripts which the function will be applied over</p>

<ul>
<li>1: indicates rows</li>
<li>2: indicates columns</li>
<li>c(1, 2): indicates rows and columns</li>
</ul></li>
<li><p>FUN: refers to the function that we want to apply on the dataset</p></li>
<li><p>&quot;...&quot; : additional arguments of FUN</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-66" style="background:;">
  <hgroup>
    <h3>apply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myMat &lt;- matrix(1:10, ncol = 5)
myMat[2,c(2, 5)] &lt;- NA
myMat
</code></pre>

<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,]    1    3    5    7    9
## [2,]    2   NA    6    8   NA
</code></pre>

<pre><code class="r">apply(myMat, 2, sum, na.rm = TRUE)
</code></pre>

<pre><code>## [1]  3  3 11 15  9
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-67" style="background:;">
  <hgroup>
    <h3>apply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r"># consider iris dataset: 
head(iris) # more info ?iris
</code></pre>

<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa
</code></pre>

<pre><code class="r"># suppose we are interested in getting 25% and 75% of each numeric column
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-68" style="background:;">
  <hgroup>
    <h3>apply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r"># Consider iris dataset: 
apply(iris[,-5], 2, quantile, probs = c(0.25, 0.75))
</code></pre>

<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width
## 25%          5.1         2.8          1.6         0.3
## 75%          6.4         3.3          5.1         1.8
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-69" style="background:;">
  <hgroup>
    <h3>lapply() and sapply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(lapply)
</code></pre>

<pre><code>## function (X, FUN, ...)
</code></pre>

<pre><code class="r">str(sapply)
</code></pre>

<pre><code>## function (X, FUN, ..., simplify = TRUE, USE.NAMES = TRUE)
</code></pre>

<ul>
<li>x: a list, dataframe, or a vector</li>
<li>FUN: the function to be applied to each element of X</li>
<li>&quot;...&quot;: other arguments of FUN</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-70" style="background:;">
  <hgroup>
    <h3>lapply() and sapply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myList &lt;- list(e1 = 1:10, e2 = -1:-10)
lapply(myList, mean)
</code></pre>

<pre><code>## $e1
## [1] 5.5
## 
## $e2
## [1] -5.5
</code></pre>

<pre><code class="r">sapply(myList, mean)
</code></pre>

<pre><code>##   e1   e2 
##  5.5 -5.5
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-71" style="background:;">
  <hgroup>
    <h3>lapply() v. sapply()?:</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>sapply() simplfies the result of lapply.</p></li>
<li><p>If the result of lapply is a list with all elements of the same length:</p>

<ul>
<li>if length == 1: sapply() returns a vector</li>
<li>if length != 1: sapply() returns a matrix</li>
</ul></li>
<li><p>otherwise, sapply() generates a list similar to lapply()</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-72" style="background:;">
  <hgroup>
    <h3>lapply() &amp; sapply() with a user-defined FUN</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myList &lt;- list(e1 = 1:10, e2 = -1:-10)
lapply(myList, function(element){return(mean(c(element[1], element[length(element)])))})
</code></pre>

<pre><code>## $e1
## [1] 5.5
## 
## $e2
## [1] -5.5
</code></pre>

<pre><code class="r">sapply(myList, function(element){return(mean(c(element[1], element[length(element)])))})
</code></pre>

<pre><code>##   e1   e2 
##  5.5 -5.5
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-73" style="background:;">
  <hgroup>
    <h3>tapply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(tapply)
</code></pre>

<pre><code>## function (X, INDEX, FUN = NULL, ..., simplify = TRUE)
</code></pre>

<ul>
<li>tapply() applies a function on a subset of a vector</li>
<li>X: is a vector </li>
<li>INDEX: list of one or more factors, each of same length as X</li>
<li>FUN: our function of interest</li>
<li>&quot;...&quot;: other arguments of FUN</li>
<li>simplify: any guess???</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-74" style="background:;">
  <hgroup>
    <h3>tapply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">HeightDF &lt;- data.frame(heigth = c(rnorm(100, 180, 3), rnorm(100, 170, 3)), gender = factor(rep(c(&quot;M&quot;, &quot;F&quot;), each = 100)))
head(HeightDF)
</code></pre>

<pre><code>##   heigth gender
## 1  179.4      M
## 2  178.1      M
## 3  182.9      M
## 4  177.3      M
## 5  183.0      M
## 6  184.2      M
</code></pre>

<pre><code class="r">tapply(HeightDF$heigth, HeightDF$gender, mean)
</code></pre>

<pre><code>##     F     M 
## 169.9 180.1
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-75" style="background:;">
  <hgroup>
    <h3>mapply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(mapply)
</code></pre>

<pre><code>## function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)
</code></pre>

<ul>
<li><p>all previous &quot;apply&quot; functions were univariate</p>

<ul>
<li>f(x, {some other parameters})</li>
</ul></li>
<li><p>What to do if we want to apply a multivariate function:</p>

<ul>
<li>f(x, y, {some other parameters}) # we can have more than 2 variables </li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-76" style="background:;">
  <hgroup>
    <h3>mapply():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">l1 &lt;- list(e1 = 1:10, e2 = 1:10)
l2 &lt;- list(e1 = -1:-10, e2 = -1:-10)
# how to get l1$e1[i] + l1$e2[i] + l2$e1[i] + l2$e2[i] ? 
mapply(sum, l1$e1, l1$e2, l2$e1, l2$e2)
</code></pre>

<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-77" style="background:;">
  <hgroup>
    <h3>split():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(split) # ?split for more info
</code></pre>

<pre><code>## function (x, f, drop = FALSE, ...)
</code></pre>

<ul>
<li>X: a vector or a data frame</li>
<li>f: factor</li>
<li>drop: should R drop empty factor levels?</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-78" style="background:;">
  <hgroup>
    <h3>split():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(HeightDF)
</code></pre>

<pre><code>## &#39;data.frame&#39;:    200 obs. of  2 variables:
##  $ heigth: num  179 178 183 177 183 ...
##  $ gender: Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 2 2 2 2 2 2 2 2 2 2 ...
</code></pre>

<pre><code class="r"># Goal: to separate Females from Males
splitData &lt;- split(HeightDF$heigth, HeightDF$gender)
str(splitData)
</code></pre>

<pre><code>## List of 2
##  $ F: num [1:100] 171 170 169 173 167 ...
##  $ M: num [1:100] 179 178 183 177 183 ...
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-79" style="background:;">
  <hgroup>
    <h2>Exercises: Analysis for Auto-Mpg Data</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>Dataset: Auto-Mpg Data from UCI Machine Learning Repository (some modification is done on the data for the exercise of this workshop)</li>
<li>Download:<a href="https://github.com/UCIDataScienceInitiative/IntroR_Workshop/tree/gh-pages/data">https://github.com/UCIDataScienceInitiative/IntroR_Workshop/tree/gh-pages/data</a></li>
<li>Variables (names saved in auto-mpg-names.txt): 

<ul>
<li>continuous: mpg, displacement, horsepower, weight, acceleration</li>
<li>discrete: cylinders, model year, origin</li>
<li>string: car name (not used in the analysis)</li>
<li>descriptions: mpg (city-cycle fuel consumption in miles per gallon), cylinders (# of cylinders), displacement (engine displacement in cu. inches), weight (vehichle weight in lbs.), accelerate (time to accelerate from O to 60 mph in sec.), model year (modulo 100), origin (1: American, 2: European, 3: Japanese).</li>
</ul></li>
<li>More information:   <a href="https://archive.ics.uci.edu/ml/datasets/Auto+MPG">https://archive.ics.uci.edu/ml/datasets/Auto+MPG</a></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-80" style="background:;">
  <hgroup>
    <h2>Questions to answer</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>Does mpg depend on the origin of the car?</li>
<li>How is mpg related with #cylinders of the car?</li>
<li>How is mpg related with other variables?</li>
<li>Predict mpg using the other variables provided in the data.</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-81" style="background:;">
  <article data-timings="">
    <ol>
<li>The exercises will generally follow the typical process of a statistical analysis. </li>
<li>30 min for R exercise for each exercise session, and 10 min for summary of FAQ.<br></li>
<li>Suggestion for the exercises

<ul>
<li>First work on the regular problems (with no &quot;optional&quot; marks) and skip the optional ones, especially if you are very new to R.</li>
<li>If you still have time after finishing all the regular problems, come back to work on the optional ones. </li>
</ul></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-82" style="background:;">
  <article data-timings="">
    <p>EX1. Import data</p>

<ul>
<li>1.1 Import the data &quot;auto-mpg.csv&quot; and store it as an object &quot;data&quot;. Check what string/symbol is used to denote missing values in the data and specify the argument &quot;na.strings&quot; for the function you used to read the data. </li>
<li>1.2 (optional) Read data file &quot;auto-mpg.data-original&quot;. What happens and why? Check the original data file.</li>
</ul>

<p>EX2. General check for the data</p>

<ul>
<li>2.1 check the top 6 rows of data; open the original data in excel or notepad and compare with the rows printed in R. Hint: need to set header = FALSE since the data starts right from the first line (no header). </li>
<li>2.2. check the dimension of data</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-83" style="background:;">
  <article data-timings="">
    <p>EX3. Add variable names to data</p>

<ul>
<li>3.1 read variable names from &quot;auto-mpg-names.txt&quot;</li>
<li>3.2 assign variable names to data</li>
<li>3.3 check if the variable names are correctly assigned. Hint: you can either print the variable names of the data or print the top rows of the data</li>
</ul>

<p>EX4. Data summary</p>

<ul>
<li>4.1. use a function to summarize the data structure and the class of each column;</li>
<li>4.2 apply function summary() on data and see how it is different from the function above. One nice thing is that it tells you #missing values for each variable</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-84" style="background:;">
  <article data-timings="">
    <p>EX5. Subset exercises </p>

<ul>
<li><p>5.1 summarize the variable mpg (use summary()). (There are 3 ways you can get the variable mpg.) Do you see something weird in the result? What might be the reason? We will get back to this later. </p></li>
<li><p>5.2 create a vector of the column indicies for the continuous variables (refer to dataset description to see which ones are continuous variables) and extract the continuous variables. Summarize the continuous variables (use summary()).</p></li>
<li><p>5.3 use the index vector you created above to extract the non-continous variables and summarize them; compare how summary() works differently for a factor variable (car_name) from a numerical variable.</p></li>
<li><p>5.4 (optional) read the help file for which(); create a vector of indices for the instances (rows) where origin is 2 or 3; create a new data that contains only the instances where origin is 2 or 3. Hint: logical operator: &amp; for and, | for or, ! for NOT.  </p></li>
<li><p>5.5 drop variable &quot;car_name&quot;. We will not use it in our analysis. Hint: you can either assign NULL (empty) to the variable &quot;car_name&quot;, or redefine data to be the subset of the data that does not contain &quot;car_name&quot;. </p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-85" style="background:;">
  <article data-timings="">
    <p>EX6. Discrete variables </p>

<ul>
<li>6.1 check and apply function table() on variable cylinders</li>
<li>6.2 use a loop to print the name and the frequency table for each discrete variable. Note that there are very few instances with odd number of cylinders. We will revisit this. Also... weird value -99 again? </li>
<li>6.3 we are going to change the data, so please first make a copy of the original data; in case you do something wrong later you can easily reset the new data to be the original data. </li>
<li>6.4 origin is a categorical variable by nature, so we are going to convert it to a factor type. But before doing that, we need to first fix the weird values &quot;-99&quot; - sometimes the coding gets messed up and the unlikely values like &quot;-99&quot; are used to code missing values - in which case we should confirm this with the data entry clerk. Now assuming this has been confirmed, let&#39;s replace all &quot;-99&quot; in origin with NA (not &quot;NA&quot;). </li>
<li>6.5 table() the new variable and check if &quot;-99&quot; is successfully replaced. </li>
<li>6.6 convert variable origin into factor type, and then add the labels for the values (1: American, 2: European, 3:Japanese). </li>
<li>6.7 check the variable type of the converted variable and the variable from the original data</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-86" style="background:;">
  <article data-timings="">
    <p>EX7. Missing values</p>

<ul>
<li>7.1 First let&#39;s also fix the &quot;-99&quot; in mpg as for origin. </li>
<li>7.2 use summary(data) to check if every variable looks reasonable now. Note: in reality, even dirtier data coding could happen, e.g. multiple bad codings, in which case histograms and boxplots will be useful - since we are able to see all weird values at the same time. Similar as checking outliers.<br></li>
<li>7.3 using is.na() function, take a subset of the dataset that has non-missing mpg and check the dimension of the subset. Hint: !is.na() refers to NOT NA. </li>
<li>7.4 write a function total_NAs(x) that returns the total number of missing values in the dataset given in the argument &quot;x&quot;. Test your function on the current data, it should return 17. </li>
<li>7.5 read the help file for function na.omit(), and use this function to create a new data that contains only the instances that has no missing value on any variables</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-87" style="background:;">
  <hgroup>
    <h1>From now on use the data set that contains no missing values</h1>
  </hgroup>
  <article data-timings="">
    <p>EX8. (optional) Exercises for *apply() and split()</p>

<ul>
<li>8.1 use one of the *apply() functions to get the frequency table on all discrete variables. Note that if these variables were all of factor type instead of numerical type, this could be directly done by summary(data[,c(2,7,8)]) </li>
<li>8.2 find average mpg for each # cylinders</li>
<li>8.3 find 2.5 and 97.5 percentile of mpg for each # cynlinders </li>
<li>8.4 split the dataset based on # cylinders </li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-88" style="background:;">
  <hgroup>
    <h2>Time for Lunch Break for 30 Minutes. Please come back at 12:30 :)</h2>
  </hgroup>
  <article data-timings="">
    
  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-89" style="background:;">
  <hgroup>
    <h2>Session 3 - Agenda</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>Useful Matrix Functions</li>
<li>Statistical Distributions in R</li>
<li>Intro to plotting in R</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-90" style="background:;">
  <hgroup>
    <h2>Useful Matrix Functions</h2>
  </hgroup>
  <article data-timings="">
    <p>Consider matrix &quot;A&quot;. We can then have:</p>

<ol class = "build incremental">
<li>t(A): transpose of A</li>
<li>solve(): to get inverse of A</li>
<li>eigen(): to get eigen values and eigen vectors (if A is symmetric)</li>
<li>We only cover solve() in this lecture</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-91" style="background:;">
  <hgroup>
    <h3>solve():</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Consider B = A %*% X (where X is an unknown matrix)</li>
<li>Then: X = solve(A, B)</li>
<li>In a special case where B = I, X = \(A^{-1}\)</li>
</ul>

<pre><code class="r">A &lt;- matrix(c(1, 2, 3, 2, 4, 5, 3, 5, 6), ncol = 3)
A
</code></pre>

<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    3
## [2,]    2    4    5
## [3,]    3    5    6
</code></pre>

<pre><code class="r"># to get inverse of A: solve(A)
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-92" style="background:;">
  <hgroup>
    <h3>solve():</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">solve(A)
</code></pre>

<pre><code>##      [,1] [,2] [,3]
## [1,]    1   -3    2
## [2,]   -3    3   -1
## [3,]    2   -1    0
</code></pre>

<pre><code class="r"># To check that solve(A) is inverse of A:
solve(A)%*%A
</code></pre>

<pre><code>##      [,1] [,2]       [,3]
## [1,]    1    0  0.000e+00
## [2,]    0    1 -8.882e-16
## [3,]    0    0  1.000e+00
</code></pre>

<ul>
<li>Machine epsilon is defined to be the smallest positive number which, when added to 1, gives a number different from 1.</li>
<li>Please visit <a href="http://en.wikipedia.org/wiki/Machine_epsilon">http://en.wikipedia.org/wiki/Machine_epsilon</a> for more info</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-93" style="background:;">
  <hgroup>
    <h2>Statistical Distributions in R:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>R has many in-built statistical distributions</p>

<ul>
<li>examples: binomial, poisson, normal, chi square, ...</li>
</ul></li>
<li><p>Each distribution in R has four functions:</p>

<ul>
<li>these functions beging with a &quot;d&quot;, &quot;p&quot;, &quot;q&quot;, or &quot;r&quot; and followed by the name of the distribution</li>
</ul></li>
<li><p>ddist(parameters): refers to the density of each distribution</p></li>
<li><p>rdist(parameters): generates random numbers out of each distribution</p></li>
<li><p>qdist(parameters): to get quantile of a distribution</p></li>
<li><p>pdist(parameters): to calculate CDF</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-94" style="background:;">
  <hgroup>
    <h3>Example of a Discrete Distribution:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r"># Consider tossing a coin 10 times
str(dbinom)
</code></pre>

<pre><code>## function (x, size, prob, log = FALSE)
</code></pre>

<pre><code class="r">dbinom(5, 10, 0.5) # prob of getting five heads
</code></pre>

<pre><code>## [1] 0.2461
</code></pre>

<pre><code class="r">str(pbinom) # cumulative dist
</code></pre>

<pre><code>## function (q, size, prob, lower.tail = TRUE, log.p = FALSE)
</code></pre>

<pre><code class="r">pbinom(5, 10, 0.5) # Pr[X &lt;= 5]
</code></pre>

<pre><code>## [1] 0.623
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-95" style="background:;">
  <hgroup>
    <h3>Example of a Discrete Distribution:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(qbinom) # quantile: Pr[X &lt;= ?] = known value
</code></pre>

<pre><code>## function (p, size, prob, lower.tail = TRUE, log.p = FALSE)
</code></pre>

<pre><code class="r">qbinom(0.6230, 10, 0.5) # get the value of ? s.t. Pr[X &lt;= ?]=0.6230
</code></pre>

<pre><code>## [1] 5
</code></pre>

<pre><code class="r">str(rbinom) # Generating random numbers
</code></pre>

<pre><code>## function (n, size, prob)
</code></pre>

<pre><code class="r">rbinom(20, 10, 0.5) # 20 ind samples from binomial(10, 0.5)
</code></pre>

<pre><code>##  [1] 5 6 5 6 4 7 5 3 7 5 3 7 5 2 5 6 4 6 6 3
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-96" style="background:;">
  <hgroup>
    <h3>Example of a Continuous Distribution:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r"># Consider a standard Normal distribution
str(dnorm)
</code></pre>

<pre><code>## function (x, mean = 0, sd = 1, log = FALSE)
</code></pre>

<pre><code class="r">dnorm(x = 0, mean = 0, sd = 1, log = FALSE)
</code></pre>

<pre><code>## [1] 0.3989
</code></pre>

<pre><code class="r">str(pnorm) # cumulative dist
</code></pre>

<pre><code>## function (q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
</code></pre>

<pre><code class="r">pnorm(0, mean = 0, sd = 1)
</code></pre>

<pre><code>## [1] 0.5
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-97" style="background:;">
  <hgroup>
    <h3>Example of a Continuous Distribution:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">str(qnorm) # quantile
</code></pre>

<pre><code>## function (p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
</code></pre>

<pre><code class="r">qnorm(0.5, mean = 0, sd = 1)
</code></pre>

<pre><code>## [1] 0
</code></pre>

<pre><code class="r">str(pnorm) # cumulative dist
</code></pre>

<pre><code>## function (q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
</code></pre>

<pre><code class="r">rnorm(10, mean = 0, sd = 1)
</code></pre>

<pre><code>##  [1] -2.0271 -0.5438  1.0976  0.3732 -0.5845 -0.8784 -1.5606  1.0805
##  [9]  1.0381  0.9862
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-98" style="background:;">
  <hgroup>
    <h3>Example of a Continuous Distribution:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r"># Let&#39;s try plotting Normal curve (more on plotting later)
x &lt;- seq(from = -3, to = 3, by = 0.05)
y &lt;- dnorm(x, mean = 0, sd = 1)
plot(x, y, type = &quot;l&quot;)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-65.png" title="plot of chunk unnamed-chunk-65" alt="plot of chunk unnamed-chunk-65" style="display: block; margin: auto;" /></p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-99" style="background:;">
  <hgroup>
    <h2>Plotting Systems in R</h2>
  </hgroup>
  <article data-timings="">
    <p>There are three main plotting systems in R:</p>

<ul>
<li>Base Plotting System</li>
<li>ggplot2</li>
<li>Lattice</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-100" style="background:;">
  <hgroup>
    <h2>Base System (intro)</h2>
  </hgroup>
  <article data-timings="">
    <p>In Base plotting system:</p>

<ul>
<li>We start with a blank canvas</li>
<li>by calling a plot function, we start our plot</li>
<li>Using annotation functions we can add more elements to our plot</li>
</ul>

<p>In general, plotting functions under the base system are:</p>

<ul>
<li>Functions to generate plots: plot()</li>
<li>Functions to annotate plots: text(), lines(), points()</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-101" style="background:;">
  <hgroup>
    <h2>Base Plotting System - Histogram</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">x &lt;- rnorm(100)
hist(x)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-66.png" title="plot of chunk unnamed-chunk-66" alt="plot of chunk unnamed-chunk-66" style="display: block; margin: auto;" /></p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-102" style="background:;">
  <hgroup>
    <h2>Base Plotting System - Scatter Plot</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">x &lt;- rnorm(100)
y &lt;- rnorm(100)
plot(x, y)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-67.png" title="plot of chunk unnamed-chunk-67" alt="plot of chunk unnamed-chunk-67" style="display: block; margin: auto;" /></p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-103" style="background:;">
  <hgroup>
    <h2>Base Plotting System - BoxPlot</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">x &lt;- rnorm(100, 0, 1)
y &lt;- rnorm(100, 1, 1)
z &lt;- rnorm(100, 2, 2)
boxplot(x, y , z)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-68.png" title="plot of chunk unnamed-chunk-68" alt="plot of chunk unnamed-chunk-68" style="display: block; margin: auto;" /></p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-104" style="background:;">
  <hgroup>
    <h2>Time for Break for 10 Minutes :)</h2>
  </hgroup>
  <article data-timings="">
    
  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-105" style="background:;">
  <hgroup>
    <h2>Session 4 - Agenda</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Goal: use ggplot2 to explore data afterwards</li>
<li>Emphasize simple examples</li>
<li>Emphasize principles</li>
<li>Some examples will be developed today</li>
<li class='..'>but there&#39;s a lot that won&#39;t be covered</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-106" style="background:;">
  <hgroup>
    <h3>Information Visualization</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Efficiency</li>
<li>Interpretability</li>
<li>Parsimony</li>
<li>ggplot2 lies in &quot;sweet spot&quot; of functionality</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-107" style="background:;">
  <hgroup>
    <h3>Hello, ggplot2</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>ggplot2 is a very popular graphics system written by Hadley Wickham</li>
<li>implementation of Leland Wilkinson&#39; Grammar of Graphics</li>
<li>I&#39;ll use the <code>diamonds</code> dataset for most of the examples.</li>
</ul>

<pre><code class="r">head(diamonds)
</code></pre>

<pre><code>##   carat       cut color clarity depth table price    x    y    z
## 1  0.23     Ideal     E     SI2  61.5    55   326 3.95 3.98 2.43
## 2  0.21   Premium     E     SI1  59.8    61   326 3.89 3.84 2.31
## 3  0.23      Good     E     VS1  56.9    65   327 4.05 4.07 2.31
## 4  0.29   Premium     I     VS2  62.4    58   334 4.20 4.23 2.63
## 5  0.31      Good     J     SI2  63.3    58   335 4.34 4.35 2.75
## 6  0.24 Very Good     J    VVS2  62.8    57   336 3.94 3.96 2.48
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-108" style="background:;">
  <hgroup>
    <h3>First ggplot2: histogram</h3>
  </hgroup>
  <article data-timings="">
    <p>Let&#39;s make a histogram!</p>

<pre><code class="r">ggplot(diamonds, aes(price)) + geom_histogram()
</code></pre>

<pre><code>## stat_bin: binwidth defaulted to range/30. Use &#39;binwidth = x&#39; to adjust this.
</code></pre>

<p><img src="assets/fig/unnamed-chunk-70.png" alt="plot of chunk unnamed-chunk-70"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-109" style="background:;">
  <hgroup>
    <h3>Gotchas</h3>
  </hgroup>
  <article data-timings="">
    <p>Easy to run into unhelpful errors</p>

<pre><code class="r">library(ggplot2)
ggplot(airquality) # :(
</code></pre>

<pre><code>## Error: No layers in plot
</code></pre>

<pre><code class="r">ggplot(airquality, aes(temp)) # :&#39;&#39;&#39;(
</code></pre>

<pre><code>## Error: No layers in plot
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-110" style="background:;">
  <hgroup>
    <h3>Now make it fancier</h3>
  </hgroup>
  <article data-timings="">
    <p>Group diamonds by cut.</p>

<pre><code class="r">m &lt;- ggplot(diamonds, aes(price))
m + geom_histogram(aes(fill=cut))
</code></pre>

<pre><code>## stat_bin: binwidth defaulted to range/30. Use &#39;binwidth = x&#39; to adjust this.
</code></pre>

<p><img src="assets/fig/unnamed-chunk-72.png" alt="plot of chunk unnamed-chunk-72"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-111" style="background:;">
  <hgroup>
    <h3>Facets are an alternative</h3>
  </hgroup>
  <article data-timings="">
    <p>Group diamonds by cut.</p>

<pre><code class="r">m &lt;- ggplot(diamonds, aes(price))
m + geom_histogram(binwidth=100) + facet_grid(cut~color)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-73.png" alt="plot of chunk unnamed-chunk-73"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-112" style="background:;">
  <hgroup>
    <h3>Let&#39;s pause for a moment</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>what&#39;s up with <code>aes</code>?</li>
<li><code>aes(x, y, ...)</code></li>
<li>allows functions of columns e.g. <code>aes(x=price^2)</code>, <code>aes(x=price/carat)</code></li>
<li>what are layers?</li>
</ul>

<pre><code>m &lt;- ggplot(diamonds, aes(price))
m + geom_histogram(aes(fill=cut))
</code></pre>

<ul>
<li>note that plots can be built up <em>incrementally</em></li>
<li>&quot;Geoms, short for geometric objects, describe the type of plot you will produce.&quot;</li>
<li>geom names always begin with <code>geom_</code></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-113" style="background:;">
  <hgroup>
    <h3>Scatterplots</h3>
  </hgroup>
  <article data-timings="">
    <p>Note: There&#39;s no &quot;scatterplot&quot; function. Use <code>geom_point</code>.</p>

<pre><code class="r">ggplot(diamonds, aes(price, carat)) + geom_point()
</code></pre>

<p><img src="assets/fig/unnamed-chunk-74.png" alt="plot of chunk unnamed-chunk-74"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-114" style="background:;">
  <hgroup>
    <h3>Log scales</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">ggplot(diamonds, aes(price, carat)) + geom_point() + scale_x_log10()
</code></pre>

<p><img src="assets/fig/unnamed-chunk-75.png" alt="plot of chunk unnamed-chunk-75"> </p>

<p>Scales begin with <code>scale_</code>, and are not only for continuous variables: also <code>datetime</code>, <code>shape</code>, <code>colour</code>, etc</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-115" style="background:;">
  <hgroup>
    <h3>Adding factors</h3>
  </hgroup>
  <article data-timings="">
    <p>Similar to histogram</p>

<pre><code class="r">ggplot(diamonds, aes(price, carat)) + geom_point(aes(colour=color, shape=cut))
</code></pre>

<p><img src="assets/fig/unnamed-chunk-76.png" alt="plot of chunk unnamed-chunk-76"> </p>

<p>Note the legend for each mapping!</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-116" style="background:;">
  <hgroup>
    <h3>Overview of components</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li><code>geom_*</code> : Geoms, short for geometric objects, describe the type of plot you will produce.</li>
<li><code>stat_*</code>: Statistical transformations transform your data before plotting</li>
<li><code>scale_*</code>: Scales control the mapping between data and aesthetics.</li>
<li><code>facet_*</code>: Facets display subsets of the dataset in different panels.</li>
<li><code>coord_*</code>: Coordinate systems adjust the mapping from coordinates to the 2d plane of the computer screen.</li>
</ul>

<p>And a few others...</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-117" style="background:;">
  <hgroup>
    <h3>Problem: overplotting, approach 1a</h3>
  </hgroup>
  <article data-timings="">
    <p>Try lowering opacity</p>

<pre><code class="r">ggplot(diamonds, aes(price, carat)) + geom_point(alpha=0.1)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-77.png" alt="plot of chunk unnamed-chunk-77"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-118" style="background:;">
  <hgroup>
    <h3>Problem: overplotting, approach 1b</h3>
  </hgroup>
  <article data-timings="">
    <p>Try mapping the inverse of a variable to opacity.</p>

<pre><code class="r">ggplot(diamonds, aes(price, carat)) + geom_point(aes(alpha=1/carat))
</code></pre>

<p><img src="assets/fig/unnamed-chunk-78.png" alt="plot of chunk unnamed-chunk-78"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-119" style="background:;">
  <hgroup>
    <h3>Problem: overplotting, approach 2</h3>
  </hgroup>
  <article data-timings="">
    <p>Shake the points around a little bit.</p>

<pre><code class="r">ggplot(diamonds, aes(price, carat)) + geom_jitter()
</code></pre>

<p><img src="assets/fig/unnamed-chunk-79.png" alt="plot of chunk unnamed-chunk-79"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-120" style="background:;">
  <hgroup>
    <h3>Problem: overplotting, approach 3</h3>
  </hgroup>
  <article data-timings="">
    <p>Bin into hexagons!</p>

<pre><code class="r">library(hexbin)
ggplot(diamonds, aes(price, carat)) + geom_hex()
</code></pre>

<p><img src="assets/fig/unnamed-chunk-80.png" alt="plot of chunk unnamed-chunk-80"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-121" style="background:;">
  <hgroup>
    <h3>Problem: overplotting, approach 4</h3>
  </hgroup>
  <article data-timings="">
    <p>Smooth with a 2d density</p>

<pre><code class="r">ggplot(diamonds, aes(price, carat)) + stat_density2d()
</code></pre>

<p><img src="assets/fig/unnamed-chunk-81.png" alt="plot of chunk unnamed-chunk-81"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-122" style="background:;">
  <hgroup>
    <h3>Something completely different: map!</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">library(maps)
states &lt;- map_data(&quot;state&quot;)
ggplot(states) + geom_polygon(aes(x=long, y=lat, group = group), colour=&quot;white&quot;)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-82.png" alt="plot of chunk unnamed-chunk-82"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-123" style="background:;">
  <hgroup>
    <h3>The world is your oyster</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">ggplot(map_data(&quot;world&quot;)) + geom_polygon(aes(x=long, y=lat, group = group), colour=&quot;white&quot;)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-83.png" alt="plot of chunk unnamed-chunk-83"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-124" style="background:;">
  <hgroup>
    <h3>What&#39;s the point?</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">ucs &lt;- data.frame(lat=c(37.870007, 33.64945), long=c(-122.270501, -117.845707))
m &lt;- ggplot(map_data(&quot;state&quot;), aes(x=long, y=lat)) + geom_polygon(aes(group=group))
m + geom_point(data=ucs, colour=&quot;red&quot;, size=5)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-84.png" alt="plot of chunk unnamed-chunk-84"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-125" style="background:;">
  <hgroup>
    <h3>FYI</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>easy to add legend titles, axis labels, etc</li>
<li><code>ggsave</code> function will save the plot to an image (or can just save via Rstudio)</li>
<li><code>+ theme_bw()</code> will create a plot more suitable for printing</li>
<li>pie charts are possible but please do not make them</li>
<li>the <code>qplot</code> function is available as a more concise option</li>
<li>there are many packages that extend ggplot2&#39;s functionality!</li>
<li>e.g. <code>bdscale</code>, <code>GGally</code>, <code>xkcd</code>, <code>ggmap</code></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-126" style="background:;">
  <hgroup>
    <h3>Notes on oddities</h3>
  </hgroup>
  <article data-timings="">
    <ul>
<li>normal R docs are not the best</li>
<li>excellent online documentation</li>
<li>default theme has grey background</li>
<li>uses British English spellings (e.g. &quot;colour&quot;)</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-127" style="background:;">
  <hgroup>
    <h2>Time for Break for 10 Minutes :)</h2>
  </hgroup>
  <article data-timings="">
    
  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-128" style="background:;">
  <hgroup>
    <h2>Session 5 - Agenda</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li>T-Test in R</li>
<li>ANOVA in R</li>
<li>Linear Regression in R</li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-129" style="background:;">
  <hgroup>
    <h2>T-Test in R</h2>
  </hgroup>
  <article data-timings="">
    <p>T-tests can be categorized into two groups:</p>

<ul>
<li>1) One-Sample t-test</li>
<li>2) two-sample t-test</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-130" style="background:;">
  <hgroup>
    <h3>One-Sample T-Test</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">oneSampData &lt;- rnorm(100, mean = 0, sd = 1)
oneSampTest.0 &lt;- t.test(oneSampData) # ?t.test
oneSampTest.0
</code></pre>

<pre><code>## 
##  One Sample t-test
## 
## data:  oneSampData
## t = -0.0571, df = 99, p-value = 0.9546
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.2136  0.2016
## sample estimates:
## mean of x 
## -0.005971
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-131" style="background:;">
  <hgroup>
    <h3>One-Sample T-Test</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">names(oneSampTest.0) # alternative to names()?? 
</code></pre>

<pre><code>## [1] &quot;statistic&quot;   &quot;parameter&quot;   &quot;p.value&quot;     &quot;conf.int&quot;    &quot;estimate&quot;   
## [6] &quot;null.value&quot;  &quot;alternative&quot; &quot;method&quot;      &quot;data.name&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-132" style="background:;">
  <hgroup>
    <h3>Two-Sample T-Test</h3>
  </hgroup>
  <article data-timings="">
    <p>Two sample t-tests are categorized into 3 groups:</p>

<ul>
<li>T-Test with equal variances</li>
<li>T-Test with un-equal variances</li>
<li>Paired T-Test: can be also considered as one-sample t-test on deltas.</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-133" style="background:;">
  <hgroup>
    <h3>Two-Sample T-Test (Un-equal Variances)</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">Samp1 &lt;- rnorm(30, mean = 2.5, sd = 1)
Samp2 &lt;- rnorm(50, mean = 5.5, sd = 1)
t.test(Samp1, Samp2)  # default assump: unequal variances
</code></pre>

<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Samp1 and Samp2
## t = -14.18, df = 47.96, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.968 -2.983
## sample estimates:
## mean of x mean of y 
##     2.190     5.665
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-134" style="background:;">
  <hgroup>
    <h3>Two-Sample T-Test (Equal Variances)</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">t.test(Samp1, Samp2, var.equal = TRUE)  # default assump: unequal variances
</code></pre>

<pre><code>## 
##  Two Sample t-test
## 
## data:  Samp1 and Samp2
## t = -15.29, df = 78, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.928 -3.023
## sample estimates:
## mean of x mean of y 
##     2.190     5.665
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-135" style="background:;">
  <hgroup>
    <h3>Two-Sample T-Test (Paired T Test)</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">t.test(Samp1, Samp2[1:30], paired = TRUE)  # default assumption: unequal variances
</code></pre>

<pre><code>## 
##  Paired t-test
## 
## data:  Samp1 and Samp2[1:30]
## t = -12.22, df = 29, p-value = 5.871e-13
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.063 -2.897
## sample estimates:
## mean of the differences 
##                   -3.48
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-136" style="background:;">
  <hgroup>
    <h2>ANOVA</h2>
  </hgroup>
  <article data-timings="">
    <p>If you are not familiar with ANOVA, simply consider ANOVA as an extension to two-sample t-test where we have more than two groups.</p>

<pre><code class="r">Samp1 &lt;- round(rnorm(10, mean = 25, sd = 1), 1)
Samp2 &lt;- round(rnorm(10, mean = 30, sd = 1), 1)
Samp3 &lt;- round(rnorm(10, mean = 35, sd = 1), 1)
myDF &lt;- data.frame(y = c(Samp1, Samp2, Samp3), group = rep(c(1, 2, 3), each = 10))
myDF$group &lt;- as.factor(myDF$group)
str(myDF)
</code></pre>

<pre><code>## &#39;data.frame&#39;:    30 obs. of  2 variables:
##  $ y    : num  24.1 25.4 24.4 25.2 25.4 24.4 24.1 24.7 25.6 25.4 ...
##  $ group: Factor w/ 3 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;: 1 1 1 1 1 1 1 1 1 1 ...
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-137" style="background:;">
  <hgroup>
    <h2>ANOVA</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">ANOVAfit &lt;- lm(y ~ group, data = myDF)  # instead of lm, aov() can also be used!
myANOVA &lt;- anova(ANOVAfit)  # anova computes analysis of variance tables on a fitted model object.
str(myANOVA) # see what is 
</code></pre>

<pre><code>## Classes &#39;anova&#39; and &#39;data.frame&#39;:    2 obs. of  5 variables:
##  $ Df     : int  2 27
##  $ Sum Sq : num  495.6 25.1
##  $ Mean Sq: num  247.78 0.93
##  $ F value: num  267 NA
##  $ Pr(&gt;F) : num  1.67e-18 NA
##  - attr(*, &quot;heading&quot;)= chr  &quot;Analysis of Variance Table\n&quot; &quot;Response: y&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-138" style="background:;">
  <hgroup>
    <h2>ANOVA</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>To learn more on how to fit ANOVA, please visit: 

<ul>
<li><a href="http://www.statmethods.net/stats/anova.html">http://www.statmethods.net/stats/anova.html</a></li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-139" style="background:;">
  <hgroup>
    <h2>Linear Regression:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>lm() is used to fit linear regression</li>
<li>Here we use &quot;Prestige&quot; dataset from &quot;car&quot; package</li>
</ul>

<pre><code class="r"># install.package(&quot;car&quot;)
library(car)
data(Prestige) # load the data
str(Prestige)
</code></pre>

<pre><code>## &#39;data.frame&#39;:    102 obs. of  6 variables:
##  $ education: num  13.1 12.3 12.8 11.4 14.6 ...
##  $ income   : int  12351 25879 9271 8865 8403 11030 8258 14163 11377 11023 ...
##  $ women    : num  11.16 4.02 15.7 9.11 11.68 ...
##  $ prestige : num  68.8 69.1 63.4 56.8 73.5 77.6 72.6 78.1 73.1 68.8 ...
##  $ census   : int  1113 1130 1171 1175 2111 2113 2133 2141 2143 2153 ...
##  $ type     : Factor w/ 3 levels &quot;bc&quot;,&quot;prof&quot;,&quot;wc&quot;: 2 2 2 2 2 2 2 2 2 2 ...
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-140" style="background:;">
  <hgroup>
    <h3>Linear Regression - Fit:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">myReg &lt;- lm(prestige ~ education + income + women, data = Prestige)
myReg # summary(myReg)
</code></pre>

<pre><code>## 
## Call:
## lm(formula = prestige ~ education + income + women, data = Prestige)
## 
## Coefficients:
## (Intercept)    education       income        women  
##    -6.79433      4.18664      0.00131     -0.00891
</code></pre>

<pre><code class="r">names(myReg)
</code></pre>

<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-141" style="background:;">
  <hgroup>
    <h3>Linear Regression - Fit:</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">head(myReg$fitted.values)
</code></pre>

<pre><code>##  gov.administrators    general.managers         accountants 
##               64.22               78.49               58.71 
## purchasing.officers            chemists          physicists 
##               52.58               65.35               73.13
</code></pre>

<pre><code class="r">head(myReg$residuals) # y - y.hat
</code></pre>

<pre><code>##  gov.administrators    general.managers         accountants 
##               4.583              -9.392               4.693 
## purchasing.officers            chemists          physicists 
##               4.219               8.152               4.472
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-142" style="background:;">
  <hgroup>
    <h2>Linear Regression - Diagnostics:</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>Here we cover some common regression diagnostics including:</p>

<ul>
<li>Testing for Normality</li>
<li>Testing for Constant Variance</li>
</ul></li>
<li><p>Reference: <a href="http://www.statmethods.net/stats/rdiagnostics.html">http://www.statmethods.net/stats/rdiagnostics.html</a></p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-143" style="background:;">
  <hgroup>
    <h3>Testing for Normality</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">qqPlot(myReg, main = &quot;QQ Plot&quot;)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-95.png" alt="plot of chunk unnamed-chunk-95"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-144" style="background:;">
  <hgroup>
    <h3>Testing for Constant Variance</h3>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">spreadLevelPlot(myReg)
</code></pre>

<p><img src="assets/fig/unnamed-chunk-96.png" alt="plot of chunk unnamed-chunk-96"> </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-145" style="background:;">
  <article data-timings="">
    <p>EX9. (optional) Randomization testing for whether mean mpg is higher for Japanese cars than European cars</p>

<ul>
<li>9.1 calculate the difference between mean mpg for Japanese cars and European cars and save in object dif_JapVSEuro</li>
<li>9.2 find the number of instances for European cars and save in object n_European</li>
<li>9.3 write a for loop that does the following in each iteration:

<ul>
<li>find the subset of European cars and Japanese cars</li>
<li>randomize the origin of the cars: randomly sample n_European instances to be &quot;European&quot; and the rest to be &quot;Japanese&quot;</li>
<li>calcualte the new difference in the mean mpg of the randomized data (Jap - Euro)</li>
<li>record whether the new difference &gt;= the observed difference, dif_JapVSEuro</li>
</ul></li>
<li>9.4 Run the simulation of 1000 iterations</li>
<li>9.5 obtain the p value by calculating the proportion of times that the difference of the randomized data &gt;= the observed difference. If this p value &lt;= the alpha level we set for the test, then we can conclude mean mpg is higher for Japanese cars than European cars. </li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-146" style="background:;">
  <article data-timings="">
    <p>EX10. Histogram of the continuous variables: to check the outliers and the distribution of the variables</p>

<ul>
<li>10.1 generate a histogram for each variable (one histogram per plot); save all plots in a pdf file and check the file. Need to install and load &quot;ggplot2&quot; package if you have not done so. </li>
<li>10.2 (optional) reshape the continuous-variable-subset of the data and use facet_grid to generate a graph that contains the histograms for all the continuous variables. Hint: melt the data so that the values of all variables go into one column and with another column (a factor) recording which variable the value is from. The variable names will be the levels of this factor. Save the graph in a pdf file and check the file. You will need the &quot;reshape2&quot; package. </li>
</ul>

<p>EX11. Boxplot of mpg by different levels of origin to visually check if mpg is different across different categories. First look up how to make a boxplot in the online ggplot2 documentation. Mpg does look different across different origin categories, suggesting mpg is likely to depend on the car origin. We will do a formal statistical test later. </p>

<ul>
<li>(optional) add an additional layer a)geom_point or b)geom_jitter() and see what happens</li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-147" style="background:;">
  <article data-timings="">
    <p>EX12. Scatterplot of mpg vs cylinders to check what the relationship is like, and to check if it is suitable to treat cylinder as a numerical variable or categorical variable.</p>

<ul>
<li><p>12.1. check the use of stat_smooth() and the argument &quot;method&quot;. Generate a scatter plot with the default smooth curve fit overlayed, and the other scatter plot with a linear regression fit overlayed. The two fitted curves should both have non-zero slopes but look quite different, suggesting mpg and cylinders are associated, but not linearly associated, in which case we want to keep cylinder as a categorical variable. You can see very few cases have cylinder = 3 or 5; sometimes you may want to do a secondary analysis with those cases removed. </p></li>
<li><p>12.2 (optional) create another data with instances with odd number of cylinders removed, and check the above plots again. The two fitted curves look similar -&gt; could treat cylinder as numerical</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-148" style="background:;">
  <article data-timings="">
    <p>EX13. Scatterplot matrix </p>

<ul>
<li>Apply function pairs() or ggpairs() on the data to create the scatterplot matrix. If you use ggpairs(), you need to install and load R package &quot;GGally&quot;.</li>
<li>to check the relationship between any pair of variable</li>
<li>to check for linearity assumption and homogeneity assumption</li>
<li>If violated, data transformation will be needed when building a linear regression model</li>
</ul>

<p>EX14. Data transformation</p>

<ul>
<li>Based on scatterplot matrix, we see increasing variance as mpg increases, and also non-linear relationship between mpg and other variables. We need to transform the variables.</li>
<li>Add new variables to the data: 

<ul>
<li>(a) log transformed versions of mpg, horsepower, displacement, and weight.</li>
<li>(b) a factor version of cylinders.</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-149" style="background:;">
  <article data-timings="">
    <p>EX15. Statistical analysis  </p>

<ul>
<li>15.1 ANOVA for origin. To formally test whether mean mpg is different across cars of the three origins. Use significance level 0.05. First build a linear regression for mpg against origin. And then use both ANOVA() and summary() to check the results. </li>
<li>15.2 linear regression. Build a linear regression model to predict mpg. Include all other variables but if a transformed version is available for a variable, use only the transformed version) (name the regression object as model); build another regression model using the same predictors but to predict log(mpg) (name the regression object as model_log). </li>
<li>15.3 Apply summary() on the regression objects and read the outputs. Is origin still helpful in predicting mpg/log(mpg) after including other predictors? </li>
<li>15.4 Which column is to answer the relationship between mpg and other variables? </li>
<li>15.5 Diagnostics (important in statistical analysis). Execute plot(model) and plot(model_log) in R and check the four plots for each model. You can find the specific help file for &quot;plot()&quot; for a lm object by executing &quot;?plot.lm&quot;. Based on the diagnostic plots, are these reasonable models? Which one is better? Check the following aspects.<br>

<ul>
<li>(a) linearity assumption, (b) normality assumption, (c) constant variance (d) outliers</li>
</ul></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-150" style="background:;">
  <article data-timings="">
    <p>EX16. (optional) An independent exercise: play with opacity setting for scatterplot of carat vs price for the diamond data. Set alpha to be different functions of the variables and see what happens </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-151" style="background:;">
  <hgroup>
    <h2>Online Resources to Learn R:</h2>
  </hgroup>
  <article data-timings="">
    <ol class = "build incremental">
<li><p>Very useful resources available on <strong>The Comprehensive R Archive Network</strong> (CRAN)</p>

<ul>
<li>please visit: <a href="http://cran.us.r-project.org">http://cran.us.r-project.org</a></li>
</ul></li>
<li><p>R built-in facility:</p>

<ul>
<li>try ?lm, help(lm) in R console</li>
</ul></li>
<li><p>There are many free tutorials available online:</p>

<ul>
<li>Quick R: <a href="http://www.statmethods.net/">http://www.statmethods.net/</a></li>
<li>R-Twotorials: <a href="http://www.twotorials.com/">http://www.twotorials.com/</a></li>
<li>UCLA Academy Technology Services: <a href="http://www.ats.ucla.edu/stat/r/">http://www.ats.ucla.edu/stat/r/</a></li>
</ul></li>
<li><p>R-Bloggers (<a href="http://www.r-bloggers.com/):">http://www.r-bloggers.com/):</a> is a central hub (e.g: A blog aggregator) of content collected from bloggers who write about R (in English). </p></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-152" style="background:;">
  <hgroup>
    <h2>Useful Books in learning R:</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li><p>Chambers(1998). Programming with Data, Springer.</p></li>
<li><p>Venables &amp; Ripley (2000). S Programming, Springer.</p></li>
<li><p>Chambers (2008). Software for Data Analysis, Springer. (highly recommended)</p></li>
<li><p>More resources available at: <a href="http://www.r-project.org/doc/bib/R-books.html">http://www.r-project.org/doc/bib/R-books.html</a></p></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-153" style="background:;">
  <hgroup>
    <h2>How to get help in R:</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li><p>Simply use the built-in help function in R</p>

<ul>
<li>example: ?lm, help(lm)</li>
</ul></li>
<li><p>R mailing lists: r-help and r-devel</p>

<ul>
<li>For more info: <a href="https://stat.ethz.ch/mailman/listinfo/r-help">https://stat.ethz.ch/mailman/listinfo/r-help</a></li>
<li>How to ask good questions: <a href="http://www.r-project.org/posting-guide.html">http://www.r-project.org/posting-guide.html</a></li>
</ul></li>
<li><p>Use Q&amp;A websites in particular:</p>

<ul>
<li>stackoverflow (<a href="http://stackoverflow.com):">http://stackoverflow.com):</a> for programming related questions.</li>
<li>crossValidated (<a href="http://stats.stackexchange.com):">http://stats.stackexchange.com):</a> for Stats related questions.</li>
</ul></li>
<li><p>Google :)  </p></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

    <slide class="backdrop"></slide>
  </slides>
  <div class="pagination pagination-small" id='io2012-ptoc' style="display:none;">
    <ul>
      <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=1 title='Introduction'>
         1
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=2 title='Introduction'>
         2
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=3 title='Session 1 - Agenda'>
         3
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=4 title='What is R?'>
         4
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=5 title='R Studio:'>
         5
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=6 title='Data Types in R:'>
         6
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=7 title='Vectors in R:'>
         7
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=8 title='Special Values:'>
         8
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=9 title='Logical, Complex, &amp; Character Vectors:'>
         9
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=10 title='Data Type Coercion:'>
         10
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=11 title='Data Type Coercion:'>
         11
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=12 title='Data Type Coercion:'>
         12
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=13 title='Factors:'>
         13
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=14 title='Factors:'>
         14
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=15 title='Factors:'>
         15
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=16 title='Missing Values:'>
         16
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=17 title='Matrices:'>
         17
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=18 title='Matrices:'>
         18
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=19 title='Matrix is a special vector:'>
         19
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=20 title='Other Ways to Create Matrix:'>
         20
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=21 title='Other Ways to Create Matrix:'>
         21
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=22 title='Lists:'>
         22
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=23 title='Lists:'>
         23
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=24 title='Data Frames:'>
         24
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=25 title='Subsetting:'>
         25
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=26 title='Subsetting examples:'>
         26
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=27 title='Subsetting with [ ]:'>
         27
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=28 title='Index Vectors:'>
         28
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=29 title='Index Vectors:'>
         29
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=30 title='Index Vectors:'>
         30
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=31 title='Logical Index Vectors:'>
         31
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=32 title='Matrix Indexing:'>
         32
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=33 title='Matrix Indexing:'>
         33
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=34 title='Subsetting Lists:'>
         34
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=35 title='Subsetting Lists:'>
         35
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=36 title='Subsetting Lists:'>
         36
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=37 title='Subsetting Data Frames:'>
         37
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=38 title='Subsetting Data Frames:'>
         38
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=39 title='Time to Break for 10 Minutes :)'>
         39
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=40 title='Session 2 - Agenda'>
         40
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=41 title='Vectorized Operations'>
         41
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=42 title='Vectorized Operations'>
         42
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=43 title='Reading and Writing Data'>
         43
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=44 title='Reading and Writing Data'>
         44
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=45 title='read.table():'>
         45
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=46 title='read.table():'>
         46
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=47 title='Calculating Memory Requirements:'>
         47
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=48 title='write.table():'>
         48
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=49 title='Loops:'>
         49
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=50 title='for:'>
         50
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=51 title='if:'>
         51
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=52 title='if:'>
         52
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=53 title='Functions and Packages:'>
         53
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=54 title='Functions and Packages:'>
         54
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=55 title='How to install a package in R:'>
         55
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=56 title='Popular Packages in R:'>
         56
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=57 title='Calling a function in R'>
         57
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=58 title='Writing your Own functions'>
         58
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=59 title='Writing your Own functions'>
         59
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=60 title='Some notes on Functions'>
         60
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=61 title='Lazy Evaluation of Function Arguments'>
         61
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=62 title='Some useful functions:'>
         62
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=63 title='str():'>
         63
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=64 title='str():'>
         64
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=65 title='apply():'>
         65
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=66 title='apply():'>
         66
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=67 title='apply():'>
         67
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=68 title='apply():'>
         68
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=69 title='lapply() and sapply():'>
         69
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=70 title='lapply() and sapply():'>
         70
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=71 title='lapply() v. sapply()?:'>
         71
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=72 title='lapply() &amp; sapply() with a user-defined FUN'>
         72
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=73 title='tapply():'>
         73
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=74 title='tapply():'>
         74
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=75 title='mapply():'>
         75
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=76 title='mapply():'>
         76
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=77 title='split():'>
         77
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=78 title='split():'>
         78
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=79 title='Exercises: Analysis for Auto-Mpg Data'>
         79
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=80 title='Questions to answer'>
         80
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=81 title=''>
         81
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=82 title=''>
         82
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=83 title=''>
         83
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=84 title=''>
         84
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=85 title=''>
         85
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=86 title=''>
         86
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=87 title='From now on use the data set that contains no missing values'>
         87
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=88 title='Time for Lunch Break for 30 Minutes. Please come back at 12:30 :)'>
         88
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=89 title='Session 3 - Agenda'>
         89
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=90 title='Useful Matrix Functions'>
         90
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=91 title='solve():'>
         91
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=92 title='solve():'>
         92
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=93 title='Statistical Distributions in R:'>
         93
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=94 title='Example of a Discrete Distribution:'>
         94
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=95 title='Example of a Discrete Distribution:'>
         95
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=96 title='Example of a Continuous Distribution:'>
         96
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=97 title='Example of a Continuous Distribution:'>
         97
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=98 title='Example of a Continuous Distribution:'>
         98
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=99 title='Plotting Systems in R'>
         99
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=100 title='Base System (intro)'>
         100
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=101 title='Base Plotting System - Histogram'>
         101
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=102 title='Base Plotting System - Scatter Plot'>
         102
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=103 title='Base Plotting System - BoxPlot'>
         103
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=104 title='Time for Break for 10 Minutes :)'>
         104
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=105 title='Session 4 - Agenda'>
         105
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=106 title='Information Visualization'>
         106
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=107 title='Hello, ggplot2'>
         107
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=108 title='First ggplot2: histogram'>
         108
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=109 title='Gotchas'>
         109
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=110 title='Now make it fancier'>
         110
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=111 title='Facets are an alternative'>
         111
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=112 title='Let&#39;s pause for a moment'>
         112
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=113 title='Scatterplots'>
         113
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=114 title='Log scales'>
         114
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=115 title='Adding factors'>
         115
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=116 title='Overview of components'>
         116
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=117 title='Problem: overplotting, approach 1a'>
         117
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=118 title='Problem: overplotting, approach 1b'>
         118
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=119 title='Problem: overplotting, approach 2'>
         119
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=120 title='Problem: overplotting, approach 3'>
         120
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=121 title='Problem: overplotting, approach 4'>
         121
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=122 title='Something completely different: map!'>
         122
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=123 title='The world is your oyster'>
         123
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=124 title='What&#39;s the point?'>
         124
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=125 title='FYI'>
         125
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=126 title='Notes on oddities'>
         126
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=127 title='Time for Break for 10 Minutes :)'>
         127
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=128 title='Session 5 - Agenda'>
         128
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=129 title='T-Test in R'>
         129
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=130 title='One-Sample T-Test'>
         130
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=131 title='One-Sample T-Test'>
         131
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=132 title='Two-Sample T-Test'>
         132
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=133 title='Two-Sample T-Test (Un-equal Variances)'>
         133
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=134 title='Two-Sample T-Test (Equal Variances)'>
         134
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=135 title='Two-Sample T-Test (Paired T Test)'>
         135
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=136 title='ANOVA'>
         136
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=137 title='ANOVA'>
         137
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=138 title='ANOVA'>
         138
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=139 title='Linear Regression:'>
         139
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=140 title='Linear Regression - Fit:'>
         140
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=141 title='Linear Regression - Fit:'>
         141
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=142 title='Linear Regression - Diagnostics:'>
         142
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=143 title='Testing for Normality'>
         143
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=144 title='Testing for Constant Variance'>
         144
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=145 title=''>
         145
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=146 title=''>
         146
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=147 title=''>
         147
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=148 title=''>
         148
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=149 title=''>
         149
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=150 title=''>
         150
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=151 title='Online Resources to Learn R:'>
         151
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=152 title='Useful Books in learning R:'>
         152
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=153 title='How to get help in R:'>
         153
      </a>
    </li>
  </ul>
  </div>  <!--[if IE]>
    <script 
      src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js">  
    </script>
    <script>CFInstall.check({mode: 'overlay'});</script>
  <![endif]-->
</body>
  <!-- Load Javascripts for Widgets -->
  
  <!-- MathJax: Fall back to local if CDN offline but local image fonts are not supported (saves >100MB) -->
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        processEscapes: true
      }
    });
  </script>
  <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <!-- <script src="https://c328740.ssl.cf1.rackcdn.com/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script> -->
  <script>window.MathJax || document.write('<script type="text/x-mathjax-config">MathJax.Hub.Config({"HTML-CSS":{imageFont:null}});<\/script><script src="libraries/widgets/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"><\/script>')
</script>
<!-- LOAD HIGHLIGHTER JS FILES -->
  <script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- DONE LOADING HIGHLIGHTER JS FILES -->
   
  </html>