---
title: "Preparing for the Introduction to R Workshop"
author: "Eric Lai"
output: pdf_document
---
### Step 0: Sign into Slack chatroom
Surf to 

https://ucidatascience.slack.com/

to gain access to the official workshop chatroom.

### Step 1: Download and install R
First, visit The R Project for Statistical Computing's website through <https://www.r-project.org/>. Click on "CRAN" under the Download section on the left-hand side of the page. Then, click on any of the nearby websites under the USA section near the bottom of the page. For example, the link from the University of California, Berkley, CA or University of California, Los Angeles, CA are both fine. Download R for your platform (Linux, Mac, or Windows).


### Step 2: Download and install RStudio
RStudio is a set of integrated tools designed to help you be more productive with R; it is known to be more user-friendly. You will be doing essentially all of your programming in RStudio. To download RStudio, go to <https://www.rstudio.com/products/rstudio/download/>. Download the installer for your platform under "Installers for Supported Platforms".

### Step 3: Installing packages
After installing R and RStudio, open RStudio. Not all functions have been installed in R, so utilizing certain functions requires you to install a package and ``open'' that package every time you open a new R session. There are two ways to install packages in RStudio.

* Method 1: Find your console (for first-time R users, the console is located at the bottom-left of RStudio's interface). Then type the following code and press Ctrl + Enter or Run (the quotation marks are needed between the package name):

```
R> install.packages("PackageName", dependencies = TRUE)
```

* Method 2: On RStudio's taskbar, click on "Tools" and then "Install Packages..." Afterwards, put down the name of the package(s) you wish to install and click install.

Before the workshop begins, please install the following packages: ggplot2. See below for example command.

```
R> install.packages("ggplot2", dependencies = TRUE)
```
